[package]
name = "xwaiter"
version = "0.1.1"
edition = "2021"
authors = ["Raycast Softworks <raycast6000@gmail.com>"]

[dependencies]
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "*"